name: Test and deploy.
on:
  push:
    branches:
      - main

jobs:
  test_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: poetry cache setup
        uses: actions/cache@v2
        with:
          path: .venv
          key: poetry-venv

      - name: install
        run: make install

      - name: lint
        run: make lint

      - name: test
        run: make test
